full_report: true # whether to generate a full PoseBusters report (i.e. with all metrics) or a summary report (i.e. with only the most important metrics)
method: diffdock # the method for which to score predictions - NOTE: must be one of (`diffdock`, `flowdock`, `neuralplexer`)
dataset: pdbbind # the dataset to use - NOTE: must be one of (`pdbbind`, `moad`)
input_csv_path: ${resolve_method_input_csv_path:${method},${dataset}} # the input CSV filepath with which to run inference
input_data_dir: ${oc.env:PROJECT_ROOT}/data/${dataset} # the input protein-ligand complex directory to recursively parse
output_dir: ${resolve_method_output_dir:${method},${dataset},${repeat_index}} # the output directory to which to save the relaxed predictions
repeat_index: 1 # the repeat index which was used for inference
